apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: akka-master
spec:
  selector:
    matchLabels:
      cluster: cluster1
      role: master
  replicas: 1
  serviceName: akka
  template:
    metadata:
      labels:
        cluster: cluster1
        role: master
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: akka-master
        image: eu.gcr.io/adam-akka/akka-cluster-kubernetes:latest
        imagePullPolicy: Always # this command makes it re-use the latest image every time that a pod spins up
        env:
            - name: clusterid
              value: cluster1
            - name: ROLE
              value: seed
            - name: SEED_NODE
              value: "akka.tcp://akka-cluster-kubernetes@akka-master-0.akka:2551"
            - name: version
              value: latest
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        ports:
        - containerPort: 2551
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akka
  labels:
    cluster: cluster1
spec:
  ports:
  - port: 2551
    name: akka
  clusterIP: None
  selector:
    cluster: cluster1
---
apiVersion: v1
kind: Service
metadata:
  name: master-http
  labels:
    cluster: cluster1
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    cluster: cluster1
    role: master