apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-master
spec:
  selector:
    matchLabels:
      cluster: cluster1
      role: master
  replicas: 1
  template:
    metadata:
      labels:
        cluster: cluster1
        role: master
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: akka-master
        image: eu.gcr.io/adam-akka/master:latest
        imagePullPolicy: Always # this command makes it re-use the latest image every time that a pod spins up
        env:
            - name: clusterid
              value: cluster1
            - name: WORKER_IMAGE
              value: eu.gcr.io/adam-akka/worker:latest
            - name: USE_KUBERNETES
              value: "true"
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        ports:
        - containerPort: 2551
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akka-master
  labels:
    cluster: cluster1
spec:
  ports:
  - port: 2551
    name: akka
  type: ClusterIP
  selector:
    cluster: cluster1
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: master-http
  labels:
    cluster: cluster1
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    cluster: cluster1
    role: master
 
 